module,execution_time (sec),success,timestamp,error,error_short
cowidev.vax.batch.argentina,3.13,True,2022-07-29T07:00:13,,
cowidev.vax.batch.australia,2.89,True,2022-07-29T07:00:13,,
cowidev.vax.batch.austria,,,2022-07-29T07:00:10,,
cowidev.vax.batch.belgium,1.82,True,2022-07-29T07:00:12,,
cowidev.vax.batch.bolivia,1.88,True,2022-07-29T07:00:12,,
cowidev.vax.batch.canada,5.9,True,2022-07-29T07:00:16,,
cowidev.vax.batch.chile,2.04,True,2022-07-29T07:00:14,,
cowidev.vax.batch.czechia,3.77,True,2022-07-29T07:00:16,,
cowidev.vax.batch.denmark,3.57,True,2022-07-29T07:00:17,,
cowidev.vax.batch.ecdc,60.08,False,2022-07-29T07:03:37,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connection.py"", line 174, in _new_conn
    conn = connection.create_connection(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/util/connection.py"", line 96, in create_connection
    raise err
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/util/connection.py"", line 86, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 699, in urlopen
    httplib_response = self._make_request(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 382, in _make_request
    self._validate_conn(conn)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 1010, in _validate_conn
    conn.connect()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connection.py"", line 358, in connect
    conn = self._new_conn()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connection.py"", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f77bddd07f0>, 'Connection to opendata.ecdc.europa.eu timed out. (connect timeout=30)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/adapters.py"", line 440, in send
    resp = conn.urlopen(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 755, in urlopen
    retries = retries.increment(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/util/retry.py"", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='opendata.ecdc.europa.eu', port=443): Max retries exceeded with url: /covid19/vaccine_tracker/csv/data.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f77bddd07f0>, 'Connection to opendata.ecdc.europa.eu timed out. (connect timeout=30)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/ecdc.py"", line 506, in main
    ECDC().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/ecdc.py"", line 496, in export
    df = self.read().pipe(self.pipe_base)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/ecdc.py"", line 111, in read
    df = read_csv_from_url(self.source_url, timeout=30)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/download.py"", line 39, in read_csv_from_url
    download_file_from_url(url, tmp.name, timeout=timeout, verify=verify, ciphers_low=ciphers_low)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/download.py"", line 52, in download_file_from_url
    r = requests.get(url, stream=True, timeout=timeout, verify=verify)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/api.py"", line 75, in get
    return request('get', url, params=params, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/api.py"", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/sessions.py"", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/sessions.py"", line 645, in send
    r = adapter.send(request, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/adapters.py"", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='opendata.ecdc.europa.eu', port=443): Max retries exceeded with url: /covid19/vaccine_tracker/csv/data.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f77bddd07f0>, 'Connection to opendata.ecdc.europa.eu timed out. (connect timeout=30)'))
","HTTPSConnectionPool(host='opendata.ecdc.europa.eu', port=443): Max retries exceeded with url: /covid19/vaccine_tracker/csv/data.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f77bddd07f0>, 'Connection to opendata.ecdc.europa.eu timed out. (connect timeout=30)'))"
cowidev.vax.batch.ecuador,1.58,True,2022-07-29T07:00:16,,
cowidev.vax.batch.estonia,0.62,True,2022-07-29T07:00:16,,
cowidev.vax.batch.france,0.53,True,2022-07-29T07:00:16,,
cowidev.vax.batch.germany,1.63,True,2022-07-29T07:00:18,,
cowidev.vax.batch.greece,2.61,True,2022-07-29T07:00:19,,
cowidev.vax.batch.hong_kong,11.97,True,2022-07-29T07:00:28,,
cowidev.vax.batch.indonesia,,,2022-07-29T07:00:17,,
cowidev.vax.batch.ireland,0.31,True,2022-07-29T07:00:17,,
cowidev.vax.batch.israel,9.41,True,2022-07-29T07:00:26,,
cowidev.vax.batch.italy,10.71,True,2022-07-29T07:00:28,,
cowidev.vax.batch.japan,1.22,False,2022-07-29T07:03:38,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 241, in main
    Japan().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 225, in export
    df = self.read().pipe(self.pipeline_base)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 161, in read
    df_latest = self.read_latest().pipe(self.pipe_latest)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 91, in read_latest
    dfs.append(self._read_xlsx(self.source_url, self.sheets, self.metrics))
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 102, in _read_xlsx
    xlsx = pd.ExcelFile(tmp.name)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/io/excel/_base.py"", line 1195, in __init__
    raise ValueError(
ValueError: Excel file format cannot be determined, you must specify an engine manually.
","Excel file format cannot be determined, you must specify an engine manually."
cowidev.vax.batch.jersey,2.17,True,2022-07-29T07:00:29,,
cowidev.vax.batch.latvia,20.3,True,2022-07-29T07:00:49,,
cowidev.vax.batch.lithuania,1.07,True,2022-07-29T07:00:29,,
cowidev.vax.batch.luxembourg,1.67,True,2022-07-29T07:00:30,,
cowidev.vax.batch.malaysia,0.96,True,2022-07-29T07:00:30,,
cowidev.vax.batch.malta,0.68,True,2022-07-29T07:00:30,,
cowidev.vax.batch.netherlands,,,2022-07-29T07:00:30,,
cowidev.vax.batch.new_zealand,11.77,True,2022-07-29T07:00:41,,
cowidev.vax.batch.norway,0.25,True,2022-07-29T07:00:30,,
cowidev.vax.batch.peru,4.32,True,2022-07-29T07:00:34,,
cowidev.vax.batch.portugal,,,2022-07-29T07:00:30,,
cowidev.vax.batch.romania,5.5,True,2022-07-29T07:00:36,,
cowidev.vax.batch.saudi_arabia,3.32,True,2022-07-29T07:00:38,,
cowidev.vax.batch.singapore,1.36,True,2022-07-29T07:00:37,,
cowidev.vax.batch.slovakia,50.21,True,2022-07-29T07:01:27,,
cowidev.vax.batch.slovenia,1.65,True,2022-07-29T07:00:39,,
cowidev.vax.batch.south_korea,11.15,True,2022-07-29T07:00:51,,
cowidev.vax.batch.spc,12.56,True,2022-07-29T07:00:54,,
cowidev.vax.batch.sweden,11.88,True,2022-07-29T07:01:00,,
cowidev.vax.batch.switzerland,33.93,True,2022-07-29T07:01:25,,
cowidev.vax.batch.trinidad_and_tobago,1.87,True,2022-07-29T07:00:56,,
cowidev.vax.batch.ukraine,,,2022-07-29T07:00:56,,
cowidev.vax.batch.united_kingdom,7.05,True,2022-07-29T07:01:03,,
cowidev.vax.batch.united_states,35.98,True,2022-07-29T07:01:36,,
cowidev.vax.batch.uruguay,3.82,True,2022-07-29T07:01:07,,
cowidev.vax.batch.zimbabwe,1.18,True,2022-07-29T07:01:08,,
cowidev.vax.incremental.africacdc,,,2022-07-29T07:01:08,,
cowidev.vax.incremental.antigua_barbuda,7.63,True,2022-07-29T07:01:15,,
cowidev.vax.incremental.aruba,1.42,True,2022-07-29T07:01:15,,
cowidev.vax.incremental.azerbaijan,14.71,True,2022-07-29T07:01:30,,
cowidev.vax.incremental.bahrain,5.56,True,2022-07-29T07:01:21,,
cowidev.vax.incremental.bangladesh,18.96,True,2022-07-29T07:01:40,,
cowidev.vax.incremental.barbados,4.09,True,2022-07-29T07:01:29,,
cowidev.vax.incremental.brazil,0.09,True,2022-07-29T07:01:28,,
cowidev.vax.incremental.bulgaria,0.94,True,2022-07-29T07:01:28,,
cowidev.vax.incremental.china,41.65,True,2022-07-29T07:02:10,,
cowidev.vax.incremental.costa_rica,,,2022-07-29T07:01:29,,
cowidev.vax.incremental.croatia,0.23,True,2022-07-29T07:01:29,,
cowidev.vax.incremental.cuba,2.19,True,2022-07-29T07:01:31,,
cowidev.vax.incremental.curacao,0.4,True,2022-07-29T07:01:30,,
cowidev.vax.incremental.cyprus,1.57,True,2022-07-29T07:01:32,,
cowidev.vax.incremental.dominican_republic,5.79,True,2022-07-29T07:01:37,,
cowidev.vax.incremental.el_salvador,1.08,True,2022-07-29T07:01:33,,
cowidev.vax.incremental.faeroe_islands,0.37,True,2022-07-29T07:01:33,,
cowidev.vax.incremental.fiji,0.0,True,2022-07-29T07:01:33,,
cowidev.vax.incremental.finland,0.24,True,2022-07-29T07:01:33,,
cowidev.vax.incremental.gabon,,,2022-07-29T07:01:33,,
cowidev.vax.incremental.georgia,0.55,True,2022-07-29T07:01:34,,
cowidev.vax.incremental.greenland,0.66,True,2022-07-29T07:01:35,,
cowidev.vax.incremental.guatemala,,,2022-07-29T07:01:35,,
cowidev.vax.incremental.guernsey,0.21,True,2022-07-29T07:01:35,,
cowidev.vax.incremental.hungary,1.06,True,2022-07-29T07:01:36,,
cowidev.vax.incremental.iceland,0.53,True,2022-07-29T07:01:36,,
cowidev.vax.incremental.india,0.92,True,2022-07-29T07:01:37,,
cowidev.vax.incremental.iran,1.83,True,2022-07-29T07:01:38,,
cowidev.vax.incremental.isle_of_man,0.44,True,2022-07-29T07:01:37,,
cowidev.vax.incremental.jamaica,2.82,False,2022-07-29T07:03:41,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/jamaica.py"", line 57, in main
    Jamaica().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/jamaica.py"", line 52, in export
    data = self.read().pipe(self.pipeline)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/jamaica.py"", line 17, in read
    return self._parse_data(soup)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/jamaica.py"", line 21, in _parse_data
    assert len(counters) == 6, ""New counter in dashboard?""
AssertionError: New counter in dashboard?
",New counter in dashboard?
cowidev.vax.incremental.kazakhstan,8.19,True,2022-07-29T07:01:46,,
cowidev.vax.incremental.kosovo,1.75,True,2022-07-29T07:01:40,,
cowidev.vax.incremental.kyrgyzstan,2.57,True,2022-07-29T07:01:42,,
cowidev.vax.incremental.laos,2.11,True,2022-07-29T07:01:42,,
cowidev.vax.incremental.macao,25.57,True,2022-07-29T07:02:07,,
cowidev.vax.incremental.moldova,1.21,True,2022-07-29T07:01:43,,
cowidev.vax.incremental.monaco,26.88,True,2022-07-29T07:02:09,,
cowidev.vax.incremental.mongolia,0.78,True,2022-07-29T07:01:44,,
cowidev.vax.incremental.montenegro,0.08,True,2022-07-29T07:01:44,,
cowidev.vax.incremental.morocco,,,2022-07-29T07:01:44,,
cowidev.vax.incremental.myanmar,,,2022-07-29T07:01:44,,
cowidev.vax.incremental.nepal,,,2022-07-29T07:01:44,,
cowidev.vax.incremental.north_macedonia,,,2022-07-29T07:01:44,,
cowidev.vax.incremental.northern_cyprus,0.8,True,2022-07-29T07:01:45,,
cowidev.vax.incremental.paho,52.03,True,2022-07-29T07:02:37,,
cowidev.vax.incremental.pakistan,1.34,True,2022-07-29T07:01:47,,
cowidev.vax.incremental.philippines,,,2022-07-29T07:01:47,,
cowidev.vax.incremental.poland,0.13,True,2022-07-29T07:01:47,,
cowidev.vax.incremental.qatar,,,2022-07-29T07:01:47,,
cowidev.vax.incremental.russia,0.67,False,2022-07-29T07:03:42,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/russia.py"", line 64, in main
    data = read(source).pipe(pipeline)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/russia.py"", line 11, in read
    soup = get_soup(source)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 52, in get_response
    raise ValueError(
ValueError: Source https://gogov.ru/articles/covid-v-stats not reached! Error code 502 Bad Gateway
",Source https://gogov.ru/articles/covid-v-stats not reached! Error code 502 Bad Gateway
cowidev.vax.incremental.saint_lucia,,,2022-07-29T07:01:49,,
cowidev.vax.incremental.serbia,6.48,True,2022-07-29T07:01:55,,
cowidev.vax.incremental.south_africa,7.08,True,2022-07-29T07:02:02,,
cowidev.vax.incremental.spain,4.92,True,2022-07-29T07:02:07,,
cowidev.vax.incremental.sri_lanka,,,2022-07-29T07:02:07,,
cowidev.vax.incremental.suriname,14.86,True,2022-07-29T07:02:21,,
cowidev.vax.incremental.taiwan,8.44,True,2022-07-29T07:02:15,,
cowidev.vax.incremental.thailand,1.76,True,2022-07-29T07:02:11,,
cowidev.vax.incremental.turkey,0.65,True,2022-07-29T07:02:11,,
cowidev.vax.incremental.united_arab_emirates,,,2022-07-29T07:02:11,,
cowidev.vax.incremental.vietnam,,,2022-07-29T07:02:11,,
cowidev.vax.incremental.who,4.18,True,2022-07-29T07:02:15,,
cowidev.vax.incremental.zambia,0.64,True,2022-07-29T07:02:12,,
