module,execution_time (sec),success,timestamp,error,error_short
cowidev.vax.batch.argentina,4.52,True,2022-08-30T07:00:22,,
cowidev.vax.batch.australia,46.53,True,2022-08-30T07:01:04,,
cowidev.vax.batch.austria,2.11,True,2022-08-30T07:00:20,,
cowidev.vax.batch.belgium,1.32,True,2022-08-30T07:00:19,,
cowidev.vax.batch.bolivia,3.53,True,2022-08-30T07:00:21,,
cowidev.vax.batch.canada,7.58,True,2022-08-30T07:00:26,,
cowidev.vax.batch.chile,0.95,True,2022-08-30T07:00:20,,
cowidev.vax.batch.czechia,3.36,True,2022-08-30T07:00:24,,
cowidev.vax.batch.denmark,9.45,True,2022-08-30T07:00:30,,
cowidev.vax.batch.ecdc,172.12,True,2022-08-30T07:03:14,,
cowidev.vax.batch.ecuador,3.19,True,2022-08-30T07:00:27,,
cowidev.vax.batch.estonia,0.73,True,2022-08-30T07:00:27,,
cowidev.vax.batch.france,1.88,True,2022-08-30T07:00:29,,
cowidev.vax.batch.germany,2.96,True,2022-08-30T07:00:30,,
cowidev.vax.batch.greece,4.86,True,2022-08-30T07:00:34,,
cowidev.vax.batch.hong_kong,17.7,True,2022-08-30T07:00:48,,
cowidev.vax.batch.indonesia,,,2022-08-30T07:00:30,,
cowidev.vax.batch.ireland,6.25,True,2022-08-30T07:00:37,,
cowidev.vax.batch.israel,12.57,True,2022-08-30T07:00:46,,
cowidev.vax.batch.italy,10.98,True,2022-08-30T07:00:48,,
cowidev.vax.batch.japan,200.35,True,2022-08-30T07:04:07,,
cowidev.vax.batch.jersey,1.88,True,2022-08-30T07:00:50,,
cowidev.vax.batch.latvia,19.69,True,2022-08-30T07:01:07,,
cowidev.vax.batch.lithuania,5.15,True,2022-08-30T07:00:55,,
cowidev.vax.batch.luxembourg,9.3,True,2022-08-30T07:01:04,,
cowidev.vax.batch.malaysia,2.81,True,2022-08-30T07:01:07,,
cowidev.vax.batch.malta,2.32,True,2022-08-30T07:01:06,,
cowidev.vax.batch.netherlands,,,2022-08-30T07:01:06,,
cowidev.vax.batch.new_zealand,15.5,True,2022-08-30T07:01:22,,
cowidev.vax.batch.norway,1.57,True,2022-08-30T07:01:08,,
cowidev.vax.batch.peru,5.46,True,2022-08-30T07:01:13,,
cowidev.vax.batch.portugal,,,2022-08-30T07:01:08,,
cowidev.vax.batch.romania,18.42,True,2022-08-30T07:01:27,,
cowidev.vax.batch.saudi_arabia,12.69,True,2022-08-30T07:01:26,,
cowidev.vax.batch.singapore,1.85,True,2022-08-30T07:01:24,,
cowidev.vax.batch.slovakia,108.18,True,2022-08-30T07:03:12,,
cowidev.vax.batch.slovenia,2.19,True,2022-08-30T07:01:28,,
cowidev.vax.batch.south_korea,51.2,True,2022-08-30T07:02:18,,
cowidev.vax.batch.spc,21.98,True,2022-08-30T07:01:50,,
cowidev.vax.batch.sweden,23.13,True,2022-08-30T07:02:13,,
cowidev.vax.batch.switzerland,53.81,True,2022-08-30T07:03:07,,
cowidev.vax.batch.trinidad_and_tobago,2.03,True,2022-08-30T07:02:20,,
cowidev.vax.batch.ukraine,,,2022-08-30T07:02:20,,
cowidev.vax.batch.united_kingdom,33.67,True,2022-08-30T07:02:54,,
cowidev.vax.batch.united_states,37.68,True,2022-08-30T07:03:31,,
cowidev.vax.batch.uruguay,5.73,True,2022-08-30T07:03:12,,
cowidev.vax.batch.zimbabwe,0.46,True,2022-08-30T07:03:12,,
cowidev.vax.incremental.africacdc,,,2022-08-30T07:03:12,,
cowidev.vax.incremental.antigua_barbuda,5.85,True,2022-08-30T07:03:18,,
cowidev.vax.incremental.aruba,1.19,True,2022-08-30T07:03:14,,
cowidev.vax.incremental.azerbaijan,5.61,False,2022-08-30T07:05:05,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/azerbaijan.py"", line 113, in main
    Azerbaijan().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/azerbaijan.py"", line 108, in export
    data = self.read().pipe(self.pipeline)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/azerbaijan.py"", line 26, in read
    data = self._parse_data(soup)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/azerbaijan.py"", line 37, in _parse_data
    text = self._parse_pdf_text(url)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/azerbaijan.py"", line 69, in _parse_pdf_text
    text = extract_text(f)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pdfminer/high_level.py"", line 146, in extract_text
    for page in PDFPage.get_pages(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pdfminer/pdfpage.py"", line 147, in get_pages
    doc = PDFDocument(parser, password=password, caching=caching)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pdfminer/pdfdocument.py"", line 726, in __init__
    raise PDFSyntaxError('No /Root object! - Is this really a PDF?')
pdfminer.pdfparser.PDFSyntaxError: No /Root object! - Is this really a PDF?
",No /Root object! - Is this really a PDF?
cowidev.vax.incremental.bahrain,1.25,True,2022-08-30T07:03:15,,
cowidev.vax.incremental.bangladesh,20.8,True,2022-08-30T07:03:36,,
cowidev.vax.incremental.barbados,2.82,True,2022-08-30T07:03:21,,
cowidev.vax.incremental.brazil,0.87,True,2022-08-30T07:03:22,,
cowidev.vax.incremental.bulgaria,2.61,True,2022-08-30T07:03:24,,
cowidev.vax.incremental.china,42.0,True,2022-08-30T07:04:04,,
cowidev.vax.incremental.costa_rica,,,2022-08-30T07:03:24,,
cowidev.vax.incremental.croatia,3.55,True,2022-08-30T07:03:27,,
cowidev.vax.incremental.cuba,3.36,True,2022-08-30T07:03:30,,
cowidev.vax.incremental.curacao,1.34,True,2022-08-30T07:03:32,,
cowidev.vax.incremental.cyprus,0.7,True,2022-08-30T07:03:32,,
cowidev.vax.incremental.dominican_republic,7.36,True,2022-08-30T07:03:39,,
cowidev.vax.incremental.el_salvador,0.78,True,2022-08-30T07:03:33,,
cowidev.vax.incremental.faeroe_islands,0.3,True,2022-08-30T07:03:33,,
cowidev.vax.incremental.fiji,0.0,True,2022-08-30T07:03:33,,
cowidev.vax.incremental.finland,0.24,True,2022-08-30T07:03:33,,
cowidev.vax.incremental.gabon,,,2022-08-30T07:03:33,,
cowidev.vax.incremental.georgia,0.62,True,2022-08-30T07:03:34,,
cowidev.vax.incremental.greenland,0.58,True,2022-08-30T07:03:35,,
cowidev.vax.incremental.guatemala,,,2022-08-30T07:03:35,,
cowidev.vax.incremental.guernsey,0.29,True,2022-08-30T07:03:35,,
cowidev.vax.incremental.hungary,0.97,True,2022-08-30T07:03:36,,
cowidev.vax.incremental.iceland,1.06,True,2022-08-30T07:03:37,,
cowidev.vax.incremental.india,1.65,True,2022-08-30T07:03:38,,
cowidev.vax.incremental.iran,2.56,True,2022-08-30T07:03:39,,
cowidev.vax.incremental.isle_of_man,3.3,True,2022-08-30T07:03:41,,
cowidev.vax.incremental.jamaica,10.68,True,2022-08-30T07:03:50,,
cowidev.vax.incremental.kazakhstan,16.85,True,2022-08-30T07:03:56,,
cowidev.vax.incremental.kosovo,12.54,False,2022-08-30T07:05:18,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/kosovo.py"", line 82, in main
    Kosovo().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/kosovo.py"", line 77, in export
    df = self.read().pipe(self.pipeline)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/kosovo.py"", line 23, in read
    df = self._parse_data(soup)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/kosovo.py"", line 32, in _parse_data
    soup = get_soup(link, verify=False)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 52, in get_response
    raise ValueError(
ValueError: Source https://msh.rks-gov.net/10.230.0.57+9000/coviddashboard.html not reached! Error code 404 Not Found
",Source https://msh.rks-gov.net/10.230.0.57+9000/coviddashboard.html not reached! Error code 404 Not Found
cowidev.vax.incremental.kyrgyzstan,3.36,True,2022-08-30T07:03:53,,
cowidev.vax.incremental.laos,3.48,True,2022-08-30T07:03:55,,
cowidev.vax.incremental.macao,17.22,True,2022-08-30T07:04:10,,
cowidev.vax.incremental.moldova,43.29,False,2022-08-30T07:06:01,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connection.py"", line 174, in _new_conn
    conn = connection.create_connection(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/util/connection.py"", line 96, in create_connection
    raise err
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/util/connection.py"", line 86, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 699, in urlopen
    httplib_response = self._make_request(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 382, in _make_request
    self._validate_conn(conn)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 1010, in _validate_conn
    conn.connect()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connection.py"", line 358, in connect
    conn = self._new_conn()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connection.py"", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f9a3631f0a0>, 'Connection to vaccinare.gov.md timed out. (connect timeout=20)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/adapters.py"", line 440, in send
    resp = conn.urlopen(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 755, in urlopen
    retries = retries.increment(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/util/retry.py"", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='vaccinare.gov.md', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f9a3631f0a0>, 'Connection to vaccinare.gov.md timed out. (connect timeout=20)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/moldova.py"", line 59, in main
    Moldova().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/moldova.py"", line 54, in export
    df = self.read().pipe(self.pipeline)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/moldova.py"", line 17, in read
    soup = get_soup(self.source_url)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 49, in get_response
    raise err
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 43, in get_response
    response = requests.get(source, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/api.py"", line 75, in get
    return request('get', url, params=params, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/api.py"", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/sessions.py"", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/sessions.py"", line 645, in send
    r = adapter.send(request, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/adapters.py"", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='vaccinare.gov.md', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f9a3631f0a0>, 'Connection to vaccinare.gov.md timed out. (connect timeout=20)'))
","HTTPSConnectionPool(host='vaccinare.gov.md', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f9a3631f0a0>, 'Connection to vaccinare.gov.md timed out. (connect timeout=20)'))"
cowidev.vax.incremental.monaco,54.83,True,2022-08-30T07:04:51,,
cowidev.vax.incremental.mongolia,1.17,True,2022-08-30T07:04:05,,
cowidev.vax.incremental.montenegro,0.56,True,2022-08-30T07:04:05,,
cowidev.vax.incremental.morocco,,,2022-08-30T07:04:05,,
cowidev.vax.incremental.myanmar,,,2022-08-30T07:04:05,,
cowidev.vax.incremental.nepal,,,2022-08-30T07:04:05,,
cowidev.vax.incremental.north_macedonia,,,2022-08-30T07:04:05,,
cowidev.vax.incremental.northern_cyprus,1.74,True,2022-08-30T07:04:07,,
cowidev.vax.incremental.paho,53.05,True,2022-08-30T07:05:00,,
cowidev.vax.incremental.pakistan,6.66,True,2022-08-30T07:04:14,,
cowidev.vax.incremental.philippines,,,2022-08-30T07:04:10,,
cowidev.vax.incremental.poland,1.52,True,2022-08-30T07:04:12,,
cowidev.vax.incremental.qatar,,,2022-08-30T07:04:12,,
cowidev.vax.incremental.russia,1.48,False,2022-08-30T07:06:03,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/russia.py"", line 80, in main
    Russia().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/russia.py"", line 66, in export
    data = read(source).pipe(pipeline)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/russia.py"", line 11, in read
    soup = get_soup(source)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 52, in get_response
    raise ValueError(
ValueError: Source https://gogov.ru/articles/covid-v-stats not reached! Error code 502 Bad Gateway
",Source https://gogov.ru/articles/covid-v-stats not reached! Error code 502 Bad Gateway
cowidev.vax.incremental.saint_lucia,,,2022-08-30T07:04:13,,
cowidev.vax.incremental.serbia,6.09,True,2022-08-30T07:04:19,,
cowidev.vax.incremental.south_africa,17.44,True,2022-08-30T07:04:31,,
cowidev.vax.incremental.spain,13.43,True,2022-08-30T07:04:32,,
cowidev.vax.incremental.sri_lanka,,,2022-08-30T07:04:31,,
cowidev.vax.incremental.suriname,17.08,True,2022-08-30T07:04:48,,
cowidev.vax.incremental.taiwan,5.89,True,2022-08-30T07:04:38,,
cowidev.vax.incremental.thailand,3.28,True,2022-08-30T07:04:39,,
cowidev.vax.incremental.turkey,0.51,True,2022-08-30T07:04:39,,
cowidev.vax.incremental.united_arab_emirates,,,2022-08-30T07:04:39,,
cowidev.vax.incremental.vietnam,,,2022-08-30T07:04:39,,
cowidev.vax.incremental.who,4.8,True,2022-08-30T07:04:43,,
cowidev.vax.incremental.zambia,1.3,True,2022-08-30T07:04:40,,
