module,execution_time (sec),success,timestamp,error,error_short
cowidev.vax.batch.argentina,3.5,True,2022-08-03T07:00:12,,
cowidev.vax.batch.australia,1.65,True,2022-08-03T07:00:11,,
cowidev.vax.batch.austria,,,2022-08-03T07:00:09,,
cowidev.vax.batch.belgium,2.26,True,2022-08-03T07:00:11,,
cowidev.vax.batch.bolivia,2.52,True,2022-08-03T07:00:11,,
cowidev.vax.batch.canada,4.94,True,2022-08-03T07:00:14,,
cowidev.vax.batch.chile,0.72,True,2022-08-03T07:00:11,,
cowidev.vax.batch.czechia,1.42,True,2022-08-03T07:00:13,,
cowidev.vax.batch.denmark,2.69,True,2022-08-03T07:00:14,,
cowidev.vax.batch.ecdc,60.06,False,2022-08-03T07:04:05,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connection.py"", line 174, in _new_conn
    conn = connection.create_connection(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/util/connection.py"", line 96, in create_connection
    raise err
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/util/connection.py"", line 86, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 699, in urlopen
    httplib_response = self._make_request(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 382, in _make_request
    self._validate_conn(conn)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 1010, in _validate_conn
    conn.connect()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connection.py"", line 358, in connect
    conn = self._new_conn()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connection.py"", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f2acf2bfee0>, 'Connection to opendata.ecdc.europa.eu timed out. (connect timeout=30)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/adapters.py"", line 440, in send
    resp = conn.urlopen(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 755, in urlopen
    retries = retries.increment(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/util/retry.py"", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='opendata.ecdc.europa.eu', port=443): Max retries exceeded with url: /covid19/vaccine_tracker/csv/data.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2acf2bfee0>, 'Connection to opendata.ecdc.europa.eu timed out. (connect timeout=30)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/ecdc.py"", line 506, in main
    ECDC().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/ecdc.py"", line 496, in export
    df = self.read().pipe(self.pipe_base)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/ecdc.py"", line 111, in read
    df = read_csv_from_url(self.source_url, timeout=30)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/download.py"", line 39, in read_csv_from_url
    download_file_from_url(url, tmp.name, timeout=timeout, verify=verify, ciphers_low=ciphers_low)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/download.py"", line 52, in download_file_from_url
    r = requests.get(url, stream=True, timeout=timeout, verify=verify)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/api.py"", line 75, in get
    return request('get', url, params=params, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/api.py"", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/sessions.py"", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/sessions.py"", line 645, in send
    r = adapter.send(request, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/adapters.py"", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='opendata.ecdc.europa.eu', port=443): Max retries exceeded with url: /covid19/vaccine_tracker/csv/data.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2acf2bfee0>, 'Connection to opendata.ecdc.europa.eu timed out. (connect timeout=30)'))
","HTTPSConnectionPool(host='opendata.ecdc.europa.eu', port=443): Max retries exceeded with url: /covid19/vaccine_tracker/csv/data.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2acf2bfee0>, 'Connection to opendata.ecdc.europa.eu timed out. (connect timeout=30)'))"
cowidev.vax.batch.ecuador,1.2,True,2022-08-03T07:00:14,,
cowidev.vax.batch.estonia,0.62,True,2022-08-03T07:00:13,,
cowidev.vax.batch.france,0.73,True,2022-08-03T07:00:14,,
cowidev.vax.batch.germany,1.5,True,2022-08-03T07:00:15,,
cowidev.vax.batch.greece,3.13,True,2022-08-03T07:00:17,,
cowidev.vax.batch.hong_kong,11.1,True,2022-08-03T07:00:25,,
cowidev.vax.batch.indonesia,,,2022-08-03T07:00:14,,
cowidev.vax.batch.ireland,0.45,True,2022-08-03T07:00:14,,
cowidev.vax.batch.israel,10.34,True,2022-08-03T07:00:25,,
cowidev.vax.batch.italy,8.95,True,2022-08-03T07:00:24,,
cowidev.vax.batch.japan,0.34,False,2022-08-03T07:04:06,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 237, in main
    Japan().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 221, in export
    df = self.read().pipe(self.pipeline_base)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 157, in read
    df_latest = self.read_latest().pipe(self.pipe_latest)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 89, in read_latest
    dfs.append(self._read_xlsx(self.source_url, self.sheets, self.metrics))
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 98, in _read_xlsx
    xlsx = pd.ExcelFile(tmp.name)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/io/excel/_base.py"", line 1195, in __init__
    raise ValueError(
ValueError: Excel file format cannot be determined, you must specify an engine manually.
","Excel file format cannot be determined, you must specify an engine manually."
cowidev.vax.batch.jersey,0.94,True,2022-08-03T07:00:25,,
cowidev.vax.batch.latvia,18.53,True,2022-08-03T07:00:43,,
cowidev.vax.batch.lithuania,1.52,True,2022-08-03T07:00:27,,
cowidev.vax.batch.luxembourg,1.47,True,2022-08-03T07:00:27,,
cowidev.vax.batch.malaysia,0.65,True,2022-08-03T07:00:26,,
cowidev.vax.batch.malta,0.73,True,2022-08-03T07:00:27,,
cowidev.vax.batch.netherlands,,,2022-08-03T07:00:27,,
cowidev.vax.batch.new_zealand,19.87,True,2022-08-03T07:00:46,,
cowidev.vax.batch.norway,0.76,True,2022-08-03T07:00:27,,
cowidev.vax.batch.peru,3.89,True,2022-08-03T07:00:31,,
cowidev.vax.batch.portugal,,,2022-08-03T07:00:27,,
cowidev.vax.batch.romania,7.2,True,2022-08-03T07:00:35,,
cowidev.vax.batch.saudi_arabia,6.94,True,2022-08-03T07:00:37,,
cowidev.vax.batch.singapore,2.66,True,2022-08-03T07:00:37,,
cowidev.vax.batch.slovakia,42.84,True,2022-08-03T07:01:20,,
cowidev.vax.batch.slovenia,1.87,True,2022-08-03T07:00:39,,
cowidev.vax.batch.south_korea,41.7,True,2022-08-03T07:01:21,,
cowidev.vax.batch.spc,21.12,True,2022-08-03T07:01:04,,
cowidev.vax.batch.sweden,12.59,True,2022-08-03T07:00:59,,
cowidev.vax.batch.switzerland,30.86,True,2022-08-03T07:01:30,,
cowidev.vax.batch.trinidad_and_tobago,2.17,True,2022-08-03T07:01:07,,
cowidev.vax.batch.ukraine,,,2022-08-03T07:01:07,,
cowidev.vax.batch.united_kingdom,7.89,True,2022-08-03T07:01:15,,
cowidev.vax.batch.united_states,16.06,True,2022-08-03T07:01:28,,
cowidev.vax.batch.uruguay,5.22,True,2022-08-03T07:01:20,,
cowidev.vax.batch.zimbabwe,0.63,True,2022-08-03T07:01:20,,
cowidev.vax.incremental.africacdc,,,2022-08-03T07:01:20,,
cowidev.vax.incremental.antigua_barbuda,3.54,True,2022-08-03T07:01:24,,
cowidev.vax.incremental.aruba,0.88,True,2022-08-03T07:01:21,,
cowidev.vax.incremental.azerbaijan,4.27,True,2022-08-03T07:01:25,,
cowidev.vax.incremental.bahrain,1.41,True,2022-08-03T07:01:23,,
cowidev.vax.incremental.bangladesh,16.22,True,2022-08-03T07:01:39,,
cowidev.vax.incremental.barbados,3.27,True,2022-08-03T07:01:27,,
cowidev.vax.incremental.brazil,0.07,True,2022-08-03T07:01:25,,
cowidev.vax.incremental.bulgaria,1.17,True,2022-08-03T07:01:27,,
cowidev.vax.incremental.china,98.61,True,2022-08-03T07:03:05,,
cowidev.vax.incremental.costa_rica,,,2022-08-03T07:01:27,,
cowidev.vax.incremental.croatia,0.14,True,2022-08-03T07:01:27,,
cowidev.vax.incremental.cuba,2.0,True,2022-08-03T07:01:29,,
cowidev.vax.incremental.curacao,0.37,True,2022-08-03T07:01:28,,
cowidev.vax.incremental.cyprus,0.92,True,2022-08-03T07:01:29,,
cowidev.vax.incremental.dominican_republic,6.59,True,2022-08-03T07:01:36,,
cowidev.vax.incremental.el_salvador,0.88,True,2022-08-03T07:01:30,,
cowidev.vax.incremental.faeroe_islands,0.33,True,2022-08-03T07:01:30,,
cowidev.vax.incremental.fiji,0.0,True,2022-08-03T07:01:30,,
cowidev.vax.incremental.finland,0.2,True,2022-08-03T07:01:30,,
cowidev.vax.incremental.gabon,,,2022-08-03T07:01:30,,
cowidev.vax.incremental.georgia,0.54,True,2022-08-03T07:01:31,,
cowidev.vax.incremental.greenland,0.42,True,2022-08-03T07:01:31,,
cowidev.vax.incremental.guatemala,,,2022-08-03T07:01:31,,
cowidev.vax.incremental.guernsey,0.26,True,2022-08-03T07:01:31,,
cowidev.vax.incremental.hungary,1.21,True,2022-08-03T07:01:32,,
cowidev.vax.incremental.iceland,0.27,True,2022-08-03T07:01:31,,
cowidev.vax.incremental.india,0.9,True,2022-08-03T07:01:32,,
cowidev.vax.incremental.iran,1.78,True,2022-08-03T07:01:34,,
cowidev.vax.incremental.isle_of_man,0.92,True,2022-08-03T07:01:33,,
cowidev.vax.incremental.jamaica,1.36,True,2022-08-03T07:01:34,,
cowidev.vax.incremental.kazakhstan,6.88,True,2022-08-03T07:01:41,,
cowidev.vax.incremental.kosovo,1.71,True,2022-08-03T07:01:36,,
cowidev.vax.incremental.kyrgyzstan,1.66,True,2022-08-03T07:01:37,,
cowidev.vax.incremental.laos,2.27,True,2022-08-03T07:01:38,,
cowidev.vax.incremental.macao,16.73,True,2022-08-03T07:01:54,,
cowidev.vax.incremental.moldova,0.94,True,2022-08-03T07:01:39,,
cowidev.vax.incremental.monaco,27.17,True,2022-08-03T07:02:06,,
cowidev.vax.incremental.mongolia,1.04,True,2022-08-03T07:01:40,,
cowidev.vax.incremental.montenegro,0.11,True,2022-08-03T07:01:41,,
cowidev.vax.incremental.morocco,,,2022-08-03T07:01:41,,
cowidev.vax.incremental.myanmar,,,2022-08-03T07:01:41,,
cowidev.vax.incremental.nepal,,,2022-08-03T07:01:41,,
cowidev.vax.incremental.north_macedonia,,,2022-08-03T07:01:41,,
cowidev.vax.incremental.northern_cyprus,0.77,True,2022-08-03T07:01:41,,
cowidev.vax.incremental.paho,51.3,True,2022-08-03T07:02:32,,
cowidev.vax.incremental.pakistan,1.52,True,2022-08-03T07:01:43,,
cowidev.vax.incremental.philippines,,,2022-08-03T07:01:43,,
cowidev.vax.incremental.poland,0.11,True,2022-08-03T07:01:43,,
cowidev.vax.incremental.qatar,,,2022-08-03T07:01:43,,
cowidev.vax.incremental.russia,0.44,False,2022-08-03T07:04:06,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/russia.py"", line 64, in main
    data = read(source).pipe(pipeline)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/russia.py"", line 11, in read
    soup = get_soup(source)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 52, in get_response
    raise ValueError(
ValueError: Source https://gogov.ru/articles/covid-v-stats not reached! Error code 502 Bad Gateway
",Source https://gogov.ru/articles/covid-v-stats not reached! Error code 502 Bad Gateway
cowidev.vax.incremental.saint_lucia,,,2022-08-03T07:01:43,,
cowidev.vax.incremental.serbia,6.01,True,2022-08-03T07:01:49,,
cowidev.vax.incremental.south_africa,6.22,True,2022-08-03T07:01:56,,
cowidev.vax.incremental.spain,4.19,True,2022-08-03T07:01:58,,
cowidev.vax.incremental.sri_lanka,,,2022-08-03T07:01:56,,
cowidev.vax.incremental.suriname,14.88,True,2022-08-03T07:02:11,,
cowidev.vax.incremental.taiwan,7.53,True,2022-08-03T07:02:06,,
cowidev.vax.incremental.thailand,2.13,True,2022-08-03T07:02:08,,
cowidev.vax.incremental.turkey,0.58,True,2022-08-03T07:02:07,,
cowidev.vax.incremental.united_arab_emirates,,,2022-08-03T07:02:07,,
cowidev.vax.incremental.vietnam,,,2022-08-03T07:02:07,,
cowidev.vax.incremental.who,4.43,True,2022-08-03T07:02:11,,
cowidev.vax.incremental.zambia,0.52,True,2022-08-03T07:02:08,,
