module,execution_time (sec),success,timestamp,error,error_short
cowidev.vax.batch.argentina,3.07,True,2022-05-20T07:00:11,,
cowidev.vax.batch.australia,2.06,True,2022-05-20T07:00:10,,
cowidev.vax.batch.austria,,,2022-05-20T07:00:08,,
cowidev.vax.batch.belgium,1.57,True,2022-05-20T07:00:09,,
cowidev.vax.batch.bolivia,1.95,True,2022-05-20T07:00:10,,
cowidev.vax.batch.canada,4.29,True,2022-05-20T07:00:12,,
cowidev.vax.batch.chile,0.75,True,2022-05-20T07:00:10,,
cowidev.vax.batch.czechia,2.05,False,2022-05-20T07:03:01,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/czechia.py"", line 175, in main
    Czechia().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/czechia.py"", line 160, in export
    base = read(self.source_url).pipe(base_pipeline)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/czechia.py"", line 67, in base_pipeline
    return df.pipe(check_vaccine_names).pipe(translate_vaccine_names)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/czechia.py"", line 46, in check_vaccine_names
    raise ValueError(""Found unknown vaccines: {}"".format(unknown_vaccines))
ValueError: Found unknown vaccines: {'Sinovac'}
",Found unknown vaccines: {'Sinovac'}
cowidev.vax.batch.denmark,2.45,True,2022-05-20T07:00:12,,
cowidev.vax.batch.ecdc,40.05,False,2022-05-20T07:03:41,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connection.py"", line 174, in _new_conn
    conn = connection.create_connection(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/util/connection.py"", line 96, in create_connection
    raise err
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/util/connection.py"", line 86, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 699, in urlopen
    httplib_response = self._make_request(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 382, in _make_request
    self._validate_conn(conn)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 1010, in _validate_conn
    conn.connect()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connection.py"", line 358, in connect
    conn = self._new_conn()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connection.py"", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f0c946d8ca0>, 'Connection to opendata.ecdc.europa.eu timed out. (connect timeout=20)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/adapters.py"", line 440, in send
    resp = conn.urlopen(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 755, in urlopen
    retries = retries.increment(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/util/retry.py"", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='opendata.ecdc.europa.eu', port=443): Max retries exceeded with url: /covid19/vaccine_tracker/csv/data.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0c946d8ca0>, 'Connection to opendata.ecdc.europa.eu timed out. (connect timeout=20)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/ecdc.py"", line 490, in main
    ECDC().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/ecdc.py"", line 480, in export
    df = self.read().pipe(self.pipe_base)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/ecdc.py"", line 110, in read
    df = read_csv_from_url(self.source_url, timeout=20)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/download.py"", line 39, in read_csv_from_url
    download_file_from_url(url, tmp.name, timeout=timeout, verify=verify, ciphers_low=ciphers_low)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/download.py"", line 52, in download_file_from_url
    r = requests.get(url, stream=True, timeout=timeout, verify=verify)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/api.py"", line 75, in get
    return request('get', url, params=params, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/api.py"", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/sessions.py"", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/sessions.py"", line 645, in send
    r = adapter.send(request, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/adapters.py"", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='opendata.ecdc.europa.eu', port=443): Max retries exceeded with url: /covid19/vaccine_tracker/csv/data.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0c946d8ca0>, 'Connection to opendata.ecdc.europa.eu timed out. (connect timeout=20)'))
","HTTPSConnectionPool(host='opendata.ecdc.europa.eu', port=443): Max retries exceeded with url: /covid19/vaccine_tracker/csv/data.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0c946d8ca0>, 'Connection to opendata.ecdc.europa.eu timed out. (connect timeout=20)'))"
cowidev.vax.batch.ecuador,1.25,True,2022-05-20T07:00:12,,
cowidev.vax.batch.estonia,0.68,True,2022-05-20T07:00:13,,
cowidev.vax.batch.france,0.51,True,2022-05-20T07:00:13,,
cowidev.vax.batch.germany,1.19,True,2022-05-20T07:00:14,,
cowidev.vax.batch.greece,2.45,True,2022-05-20T07:00:15,,
cowidev.vax.batch.hong_kong,2.78,True,2022-05-20T07:00:16,,
cowidev.vax.batch.indonesia,6.0,True,2022-05-20T07:00:19,,
cowidev.vax.batch.ireland,0.27,True,2022-05-20T07:00:14,,
cowidev.vax.batch.israel,5.9,True,2022-05-20T07:00:20,,
cowidev.vax.batch.italy,0.81,False,2022-05-20T07:03:42,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/italy.py"", line 184, in main
    Italy().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/italy.py"", line 166, in export
    df_base = self.read().pipe(self.pipeline_base)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/italy.py"", line 41, in read
    check_known_columns(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/utils.py"", line 164, in check_known_columns
    raise Exception(f""Unknown column(s) found: {unknown_cols}"")
Exception: Unknown column(s) found: {'d1', 'ISTAT', 'N1', 'db1', 'm', 'forn', 'reg', 'eta', 'f', 'd2', 'db2', 'dbi', 'N2', 'dpi', 'data'}
","Unknown column(s) found: {'d1', 'ISTAT', 'N1', 'db1', 'm', 'forn', 'reg', 'eta', 'f', 'd2', 'db2', 'dbi', 'N2', 'dpi', 'data'}"
cowidev.vax.batch.jersey,0.51,True,2022-05-20T07:00:16,,
cowidev.vax.batch.latvia,16.66,True,2022-05-20T07:00:33,,
cowidev.vax.batch.lithuania,2.99,True,2022-05-20T07:00:20,,
cowidev.vax.batch.luxembourg,1.7,True,2022-05-20T07:00:21,,
cowidev.vax.batch.malaysia,0.47,True,2022-05-20T07:00:20,,
cowidev.vax.batch.malta,0.61,True,2022-05-20T07:00:20,,
cowidev.vax.batch.netherlands,0.5,True,2022-05-20T07:00:20,,
cowidev.vax.batch.new_zealand,15.1,True,2022-05-20T07:00:35,,
cowidev.vax.batch.norway,0.28,True,2022-05-20T07:00:21,,
cowidev.vax.batch.peru,7.67,True,2022-05-20T07:00:28,,
cowidev.vax.batch.portugal,,,2022-05-20T07:00:21,,
cowidev.vax.batch.romania,11.43,True,2022-05-20T07:00:32,,
cowidev.vax.batch.saudi_arabia,4.42,True,2022-05-20T07:00:33,,
cowidev.vax.batch.singapore,1.39,True,2022-05-20T07:00:34,,
cowidev.vax.batch.slovakia,34.97,True,2022-05-20T07:01:08,,
cowidev.vax.batch.slovenia,0.36,True,2022-05-20T07:00:33,,
cowidev.vax.batch.south_korea,7.52,True,2022-05-20T07:00:41,,
cowidev.vax.batch.spc,6.77,True,2022-05-20T07:00:40,,
cowidev.vax.batch.sweden,4.4,True,2022-05-20T07:00:40,,
cowidev.vax.batch.switzerland,11.49,True,2022-05-20T07:00:51,,
cowidev.vax.batch.trinidad_and_tobago,0.86,True,2022-05-20T07:00:41,,
cowidev.vax.batch.ukraine,,,2022-05-20T07:00:41,,
cowidev.vax.batch.united_kingdom,5.6,True,2022-05-20T07:00:46,,
cowidev.vax.batch.united_states,30.64,True,2022-05-20T07:01:12,,
cowidev.vax.batch.uruguay,3.44,True,2022-05-20T07:00:50,,
cowidev.vax.batch.zimbabwe,0.69,True,2022-05-20T07:00:50,,
cowidev.vax.incremental.africacdc,,,2022-05-20T07:00:50,,
cowidev.vax.incremental.antigua_barbuda,4.36,True,2022-05-20T07:00:55,,
cowidev.vax.incremental.aruba,1.4,True,2022-05-20T07:00:53,,
cowidev.vax.incremental.azerbaijan,13.18,True,2022-05-20T07:01:05,,
cowidev.vax.incremental.bahrain,3.96,True,2022-05-20T07:00:57,,
cowidev.vax.incremental.bangladesh,16.59,True,2022-05-20T07:01:11,,
cowidev.vax.incremental.barbados,11.18,True,2022-05-20T07:01:08,,
cowidev.vax.incremental.brazil,0.27,True,2022-05-20T07:01:05,,
cowidev.vax.incremental.bulgaria,3.34,True,2022-05-20T07:01:08,,
cowidev.vax.incremental.china,111.42,True,2022-05-20T07:02:59,,
cowidev.vax.incremental.costa_rica,12.55,True,2022-05-20T07:01:20,,
cowidev.vax.incremental.croatia,0.19,True,2022-05-20T07:01:08,,
cowidev.vax.incremental.cuba,2.06,True,2022-05-20T07:01:10,,
cowidev.vax.incremental.curacao,0.35,True,2022-05-20T07:01:11,,
cowidev.vax.incremental.cyprus,0.9,True,2022-05-20T07:01:12,,
cowidev.vax.incremental.dominican_republic,5.86,True,2022-05-20T07:01:17,,
cowidev.vax.incremental.el_salvador,0.86,True,2022-05-20T07:01:13,,
cowidev.vax.incremental.equatorial_guinea,3.02,True,2022-05-20T07:01:15,,
cowidev.vax.incremental.faeroe_islands,0.36,True,2022-05-20T07:01:13,,
cowidev.vax.incremental.fiji,0.0,True,2022-05-20T07:01:13,,
cowidev.vax.incremental.finland,0.34,False,2022-05-20T07:03:42,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/finland.py"", line 79, in main
    Finland().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/finland.py"", line 65, in export
    data = self.read().pipe(self.pipeline)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/finland.py"", line 32, in read
    assert set(df[""Vaccination dose""]) == {""First dose"", ""Second dose"", ""Third dose"", ""All doses""}
AssertionError
",
cowidev.vax.incremental.gabon,,,2022-05-20T07:01:13,,
cowidev.vax.incremental.georgia,0.59,True,2022-05-20T07:01:14,,
cowidev.vax.incremental.greenland,1.05,True,2022-05-20T07:01:15,,
cowidev.vax.incremental.guatemala,,,2022-05-20T07:01:15,,
cowidev.vax.incremental.guernsey,0.11,True,2022-05-20T07:01:15,,
cowidev.vax.incremental.hungary,0.88,True,2022-05-20T07:01:16,,
cowidev.vax.incremental.iceland,0.24,True,2022-05-20T07:01:15,,
cowidev.vax.incremental.india,0.87,True,2022-05-20T07:01:16,,
cowidev.vax.incremental.iran,1.86,True,2022-05-20T07:01:18,,
cowidev.vax.incremental.isle_of_man,1.21,True,2022-05-20T07:01:17,,
cowidev.vax.incremental.jamaica,1.42,True,2022-05-20T07:01:19,,
cowidev.vax.incremental.japan,2.21,True,2022-05-20T07:01:20,,
cowidev.vax.incremental.kazakhstan,8.1,True,2022-05-20T07:01:26,,
cowidev.vax.incremental.kosovo,1.86,True,2022-05-20T07:01:21,,
cowidev.vax.incremental.kyrgyzstan,1.05,True,2022-05-20T07:01:21,,
cowidev.vax.incremental.laos,2.13,True,2022-05-20T07:01:23,,
cowidev.vax.incremental.macao,14.7,True,2022-05-20T07:01:35,,
cowidev.vax.incremental.moldova,1.04,True,2022-05-20T07:01:22,,
cowidev.vax.incremental.monaco,26.48,True,2022-05-20T07:01:48,,
cowidev.vax.incremental.mongolia,0.79,True,2022-05-20T07:01:23,,
cowidev.vax.incremental.montenegro,0.11,True,2022-05-20T07:01:23,,
cowidev.vax.incremental.morocco,,,2022-05-20T07:01:23,,
cowidev.vax.incremental.myanmar,14.38,True,2022-05-20T07:01:38,,
cowidev.vax.incremental.nepal,14.6,True,2022-05-20T07:01:40,,
cowidev.vax.incremental.north_macedonia,,,2022-05-20T07:01:35,,
cowidev.vax.incremental.northern_cyprus,1.13,True,2022-05-20T07:01:36,,
cowidev.vax.incremental.paho,41.06,True,2022-05-20T07:02:17,,
cowidev.vax.incremental.pakistan,1.28,True,2022-05-20T07:01:39,,
cowidev.vax.incremental.philippines,0.5,True,2022-05-20T07:01:40,,
cowidev.vax.incremental.poland,0.12,True,2022-05-20T07:01:40,,
cowidev.vax.incremental.qatar,10.55,True,2022-05-20T07:01:50,,
cowidev.vax.incremental.russia,2.55,True,2022-05-20T07:01:43,,
cowidev.vax.incremental.saint_lucia,,,2022-05-20T07:01:43,,
cowidev.vax.incremental.serbia,6.26,True,2022-05-20T07:01:49,,
cowidev.vax.incremental.south_africa,5.49,True,2022-05-20T07:01:54,,
cowidev.vax.incremental.spain,4.55,True,2022-05-20T07:01:54,,
cowidev.vax.incremental.sri_lanka,,,2022-05-20T07:01:50,,
cowidev.vax.incremental.suriname,13.91,True,2022-05-20T07:02:04,,
cowidev.vax.incremental.taiwan,5.92,True,2022-05-20T07:02:00,,
cowidev.vax.incremental.thailand,1.88,True,2022-05-20T07:01:56,,
cowidev.vax.incremental.turkey,0.7,True,2022-05-20T07:01:56,,
cowidev.vax.incremental.united_arab_emirates,15.68,True,2022-05-20T07:02:12,,
cowidev.vax.incremental.vietnam,,,2022-05-20T07:02:00,,
cowidev.vax.incremental.who,2.78,True,2022-05-20T07:02:02,,
cowidev.vax.incremental.zambia,0.64,True,2022-05-20T07:02:03,,
